name: tab_bar_bya2
description: Modified version of buttons_tabbar with disable feature
version: 0.0.1


environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
